config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users
	resources :locations
	resources :todos do
		member do
    		patch :complete
    	end
    end
	
	root to: "todos#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :todo
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :todo
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	validates_presence_of :title, :description

	mount_uploader :picture, PictureUploader

	has_many :locations

	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to todo_path(@comment.todo_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to todo_path(@comment.todo_id), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :todo_id)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :description)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :patch]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @comments = @todo.comments.all
    @comment = @todo.comments.build
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def complete
    @todo = Todo.find(params[:id])
    @todo.update_attribute(:completed, true)
    @todo.update_attribute(:completedat, Time.now)
    @todo.update_attribute(:completedby, current_user.id)
    redirect_to todo_path, notice: "Task completed! Woo!"
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :description, :priority, :picture, :completed, :completedat, :completedby, :location_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/comments/_form.html.haml
= simple_form_for(@comment) do |f|
	= f.hidden_field :todo_id
	= f.hidden_field :user_name, :value => current_user.email
	= f.input :body, label: false
	= f.button :submit

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Todo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.todo_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Todo:</strong>
  <%= @comment.todo_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Getstuffdone
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
	= favicon_link_tag 'hammer.ico'
%body
	%header
		.header_inner
			=link_to image_tag('gsdlogo.png'), root_path, id: "logo"
			%nav
				- if user_signed_in?
					%p.usertext You are  logged in as #{current_user.email}
					= link_to "To Do!", todos_path
					= link_to "Locations", locations_path
					= link_to "Sign Out", destroy_user_session_path, method: :delete
				- else
					= link_to "Log In", new_user_session_path
	%p.notice= notice
	%p.alert= alert
	= yield

app/views/locations/_form.html.haml
= simple_form_for(@location) do |f|
	= f.input :name
	= f.input :description
	= f.button :submit

app/views/locations/edit.html.haml
%h1 Edit Location

= render 'form'

= link_to 'Show', @location
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%h1 Current Locations

.wrapper_with_padding
  %a{ href: (url_for new_location_path)}
    %p.button New Location
  #notes.clearfix
    - @locations.each do |location|
      %a{ href: (url_for [location])}
        #gerbil
          %p.title #{location.name}
          %p.date #{location.description}
          %p.smalllink #{link_to 'Edit', edit_location_path(location)}&nbsp;&nbsp;&nbsp;#{link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' }}

app/views/locations/new.html.haml
%h1 New Location

= render 'form'

= link_to 'Back', locations_path

app/views/locations/show.html.haml
.wrapper_with_padding
	%h1 Name: #{@location.name}
	%p Description: #{@location.description}
	
	%button= link_to 'Edit', edit_location_path(@location)
	%button= link_to 'Back', locations_path

app/views/todos/_form.html.haml
= simple_form_for(@todo) do |f|
  = f.error_notification

  .form-inputs
    %p Title: #{f.input :title, label: false}
    %p Description of Problem: #{f.input :description, label: false}
    %p Location: #{f.collection_select :location_id, Location.all, :id, :name, prompt: true}
    %p Priority: #{f.select(:priority, options_for_select([['1 - Immediate'], ['2 - Non-immediate']]))}
    %p Picture: #{f.file_field :picture}

  .form-actions
    = f.button :submit

app/views/todos/edit.html.haml
%h1 Edit Task

= render 'form'

= link_to 'Show', @todo
= link_to 'Back', todos_path

app/views/todos/index.html.haml
.wrapper_with_padding
  #active
    %a{ href: (url_for new_todo_path)}
      %p.button New Task
    #notes.clearfix
      - @todos.reject(&:completed).sort_by(&:created_at).each do |todo|
        %a{ href: (url_for [todo])}
          #gerbil
            %p.title= todo.title
            %p.date= Location.find_by_id(todo.location_id).name if todo.location_id.present?
            %p.date #{time_ago_in_words(todo.created_at)} old
            %p.smalllink #{link_to 'Complete!', complete_todo_path(todo.id), method: :patch}&nbsp;&nbsp;&nbsp;#{link_to 'Show Details', todo}
  #completed
    %h1 <BR>Completed tasks
    #notes.clearfix
      - @todos.where(:completed => true).sort_by(&:created_at).each do |todo|
        %a{ href: (url_for [todo])}
          #completedtasks
            %p.title= todo.title
            %p.date= Location.find_by_id(todo.location_id).name if todo.location_id.present?
            %p.date #{time_ago_in_words(todo.created_at)} old
            %p.smalllink #{link_to 'Show Details', todo}, #{link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' }}

app/views/todos/new.html.haml
%h1 New Task

= render 'form'

= link_to 'Back', todos_path

app/views/todos/show.html.haml
-if !@todo.completed
	.wrapper_with_padding
		%h1= @todo.title
		%p <B>Description:</B> #{@todo.description}
		%p <B>Location:</B> #{Location.find_by_id(@todo.location_id).name} /// <B>Priority:</B> #{@todo.priority}
		= image_tag(@todo.picture_url, :width => 400) if @todo.picture.present?

		%br
		%button= link_to 'Complete!', complete_todo_path(@todo.id), method: :patch
		%button= link_to 'Edit', edit_todo_path(@todo)
		%button= link_to 'Back', todos_path

		%h3 Updates on Task
		- unless @comments.blank?
			- @comments.each do |comment|
				.comment-body
					%p <B>#{comment.body}</B>
					%p by #{comment.user_name}
		- else
			%p There are no comments on this task just yet.

		%h3 Add Update
		= render 'comments/form'
- else
	.wrapper_with_padding
		%h1= @todo.title
		%p <B>Description:</B> #{@todo.description}
		%p <B>Location:</B> #{Location.find_by_id(@todo.location_id).name} /// <B>Priority:</B> #{@todo.priority}
		%p <B>Started on #{@todo.created_at}, Finished on #{@todo.completedat}
		= image_tag(@todo.picture_url, :width => 400) if @todo.picture.present?

		%h3 Updates on Task
		- unless @comments.blank?
			- @comments.each do |comment|
				.comment-body
					%p <B>#{comment.body}</B>
					%p by #{comment.user_name}
		- else
			%p There are no comments on this task just yet.

		%h3 Add Update
		= render 'comments/form'
		%button= link_to 'Back', todos_path